"""Train the potato detector: 3 classes, 100 epochs.

Run on Kaggle (free GPU, 30 hr/week) or Colab. **Do not run this on the dev
laptop** -- the brief pins a 16 GB RAM machine with very little C: space; only
the exported weights (a few MB) come back down.

    python ml/train_yolo.py --data /kaggle/working/potato_yolo/data.yaml \
        --model yolov8s.pt --epochs 100 --imgsz 640 --batch 16

Defaults chosen deliberately:

* **yolov8s** (small) is the default, not nano. Nano is the least accurate
  variant in the family, and accuracy is what matters when a wrong answer means
  a wrong pesticide. `s` roughly triples the parameters (11.2M vs 3.2M) for a
  meaningful mAP gain, and on CPU it still lands inside the latency budget --
  verify on your own hardware with `ml/benchmark_inference.py` rather than
  taking that on trust.

  Train `yolov8n` as well (`--model yolov8n.pt`) if you want the offline /
  on-device story: ship `s` on the server, `n` in a phone build. Compare them
  with `benchmark_inference.py --model a.onnx --model b.onnx`, and pick the
  largest variant that stays inside your latency budget.

* **100 epochs** with `patience=25`. Early stopping keeps a converged run from
  burning GPU quota; 100 is the ceiling, not a promise.

* **Conservative augmentation.** No vertical flip and low hue jitter: leaf
  lesion colour *is* the diagnostic signal, and aggressive colour augmentation
  teaches the model to ignore the one feature that separates early from late
  blight. Geometry is augmented freely; colour is not.

  This matters more than usual here because the dataset is small. Augmentation
  is doing real work -- but the *wrong* augmentation on a small dataset destroys
  the signal faster than it regularises the model.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

CLASS_NAMES = ["potato_early_blight", "potato_late_blight", "potato_healthy"]

REPO_DATA_YAML = Path(__file__).resolve().parent / "data.yaml"


def read_yaml_names(path: Path) -> list[str]:
    """Parse the `names:` block. Tolerates PyYAML being absent."""
    text = path.read_text(encoding="utf-8")
    block = re.search(r"^names:\s*$(.*)", text, re.M | re.S)
    if not block:
        return []
    pairs: list[tuple[int, str]] = []
    for line in block.group(1).splitlines():
        m = re.match(r"^\s+(\d+):\s*(\S+)\s*$", line)
        if m:
            pairs.append((int(m.group(1)), m.group(2)))
        elif line.strip() and not line.startswith((" ", "\t")):
            break
    return [n for _, n in sorted(pairs)]


def preflight(args) -> bool:
    """Checks that are cheap now and expensive after a 100-epoch run.

    Every one of these has a failure mode that only shows up hours later, or --
    worse -- silently produces a model that serves wrong labels forever.
    """
    ok = True

    # 1. The repo's data.yaml is a class-order declaration, not a usable dataset.
    if args.data.resolve() == REPO_DATA_YAML.resolve():
        print(
            "ERROR: ml/data.yaml is a placeholder, not a real dataset config. Its `path:`\n"
            "       points at a directory that does not exist. Use the one generated by\n"
            "       prepare_dataset.py:\n\n"
            "         python ml/prepare_dataset.py --plantvillage ... --out <DIR>\n"
            "         python ml/train_yolo.py --data <DIR>/data.yaml\n",
            file=sys.stderr,
        )
        return False

    if not args.data.exists():
        print(f"ERROR: {args.data} does not exist.", file=sys.stderr)
        return False

    # 2. Class order lockstep. Training with a different order than the backend
    #    expects produces a model that is confidently and undetectably wrong.
    names = read_yaml_names(args.data)
    if not names:
        print(f"WARNING: could not read a names: block from {args.data}", file=sys.stderr)
    elif names != CLASS_NAMES:
        print(
            f"ERROR: class order mismatch.\n"
            f"       {args.data} has {names}\n"
            f"       expected              {CLASS_NAMES}\n"
            "       Training on this order would make every served prediction mislabelled,\n"
            "       because the backend maps model index -> taxonomy.CLASS_NAMES by position.\n"
            "       Fix data.yaml, or pass --allow-class-mismatch if you have deliberately\n"
            "       changed the taxonomy to match.",
            file=sys.stderr,
        )
        if not args.allow_class_mismatch:
            return False
        ok = False

    # 3. The dataset directory actually has images in it.
    cfg_root = args.data.parent
    train_dir = cfg_root / "images" / "train"
    if train_dir.is_dir() and not any(train_dir.iterdir()):
        print(f"ERROR: {train_dir} is empty.", file=sys.stderr)
        return False

    # 4. simplify=True needs onnxslim. Better to fail now than after training.
    if not args.no_export:
        try:
            import onnxslim  # noqa: F401
        except ImportError:
            print(
                "NOTE: onnxslim is not installed, so the ONNX export will run without\n"
                "      simplification. Install it (pip install onnxslim onnx) for a smaller,\n"
                "      faster graph. Training will proceed either way.",
                file=sys.stderr,
            )
            args.simplify = False
    return ok


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", type=Path, required=True, help="Path to data.yaml")
    ap.add_argument(
        "--model", default="yolov8s.pt",
        help="yolov8s.pt (default, accuracy) | yolov8n.pt (offline/mobile) | yolov8m.pt",
    )
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--patience", type=int, default=25)
    ap.add_argument("--device", default=0, help="0 for the Kaggle GPU, 'cpu' to force CPU")
    ap.add_argument("--project", type=Path, default=Path("runs/potato"))
    ap.add_argument("--name", default=None, help="Run name; defaults to <model>_3class_<epochs>e")
    ap.add_argument("--export-dir", type=Path, default=Path("ml/weights"))
    ap.add_argument("--no-export", action="store_true")
    ap.add_argument("--no-simplify", dest="simplify", action="store_false",
                    help="Skip onnxslim graph simplification on export")
    ap.add_argument("--allow-class-mismatch", action="store_true",
                    help="Train even if data.yaml class order differs from CLASS_NAMES")
    args = ap.parse_args()
    if args.name is None:
        args.name = f"{Path(args.model).stem}_3class_{args.epochs}e"

    if not preflight(args):
        return 1

    from ultralytics import YOLO

    model = YOLO(args.model)
    results = model.train(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        patience=args.patience,
        device=args.device,
        project=str(args.project),
        name=args.name,
        seed=42,
        deterministic=True,
        pretrained=True,
        optimizer="auto",
        cos_lr=True,
        # --- augmentation: geometry yes, colour sparingly ---
        hsv_h=0.010,   # hue is the diagnostic signal -- barely touch it
        hsv_s=0.5,
        hsv_v=0.3,
        degrees=15.0,
        translate=0.10,
        scale=0.40,
        fliplr=0.5,
        flipud=0.0,    # leaves are photographed the right way up
        mosaic=1.0,
        close_mosaic=10,  # last 10 epochs without mosaic, so val matches reality
        plots=True,
        val=True,
    )

    # `model.trainer.save_dir` is the authoritative run directory. Ultralytics
    # has moved `save_dir` between the trainer and the returned metrics object
    # across versions, so read the trainer first and fall back rather than
    # relying on either one being present.
    save_dir = Path(
        getattr(getattr(model, "trainer", None), "save_dir", None)
        or getattr(results, "save_dir", None)
        or (args.project / args.name)
    )
    best = save_dir / "weights" / "best.pt"
    print(f"\nRun directory: {save_dir}")
    print(f"Best weights:  {best}")

    # `model.train()` already runs a final validation pass on best.pt, and
    # `results` IS that pass's metrics. Calling model.val() again here repeated
    # the identical computation and burned GPU quota for nothing.
    metrics = results
    summary = {
        "model": args.model,
        "epochs_requested": args.epochs,
        "imgsz": args.imgsz,
        "classes": CLASS_NAMES,
        "map50": float(getattr(metrics.box, "map50", 0.0)),
        "map50_95": float(getattr(metrics.box, "map", 0.0)),
        "precision": float(getattr(metrics.box, "mp", 0.0)),
        "recall": float(getattr(metrics.box, "mr", 0.0)),
        "per_class_map50": {
            CLASS_NAMES[i]: float(v)
            for i, v in enumerate(getattr(metrics.box, "maps", []) or [])
            if i < len(CLASS_NAMES)
        },
    }
    print("\nValidation summary:")
    print(json.dumps(summary, indent=2))

    if not args.no_export and best.exists():
        args.export_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(best, args.export_dir / "best.pt")
        (args.export_dir / "metrics.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

        # ONNX is the serving artifact -- CPU-fast and torch-free at runtime.
        # Delegate to export_onnx.py rather than duplicating the export call.
        # Two exports with independently-chosen opset and simplify settings
        # meant you could be serving one artifact while believing you had
        # validated the other. export_onnx.py is the single authority, and it
        # verifies the output shape and class count before returning.
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from export_onnx import export_and_verify

        onnx_path = export_and_verify(
            weights=best,
            out=args.export_dir / "best.onnx",
            imgsz=args.imgsz,
            simplify=args.simplify,
        )
        if onnx_path is None:
            print(
                "\nONNX export or verification FAILED. best.pt is saved, but do not deploy "
                "until `python ml/export_onnx.py` succeeds.",
                file=sys.stderr,
            )
            return 1
        print(f"\nExported to {args.export_dir}/best.pt and best.onnx")
        print("Download ml/weights/ from Kaggle and drop it into the repo -- that is the only")
        print("artifact the laptop needs; the backend picks it up on the next request.")
        print("\nNext, in this order:")
        print(f"  python ml/evaluate.py        --weights {best} --data {args.data}")
        print(f"  python ml/tune_thresholds.py --weights {best} --data {args.data}")
        print("  python ml/benchmark_inference.py --model ml/weights/best.onnx")
        print("\nThe mAP above is measured on whatever mix prepare_dataset.py built. If that")
        print("was PlantVillage only it is a LAB number -- evaluate.py separates lab from field.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
