// Runs a real ONNX model through onnxruntime-web and decodes it with the same
// code the browser uses.
//
// The other tests exercise the decoder against hand-built tensors. This one
// closes the remaining gap: that onnxruntime-web actually loads a YOLO-shaped
// model, that the tensor layout coming out of it is what the decoder expects,
// and that the result matches the Python server byte for byte. Everything
// except the camera itself is covered here.
//
// The fixture is generated by scripts/make-test-onnx.mjs (via the Python helper
// in backend/tests/test_onnx_integration.py) and skipped if absent, so the
// suite still runs on a machine without it.
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { decodeDetections, letterboxParams } from '../yoloDecode.js'

const FIXTURE = join(process.cwd(), 'src/lib/__tests__/fixtures/yolo3class.onnx')
const CLASS_NAMES = ['potato_early_blight', 'potato_late_blight', 'potato_healthy']

const describeIfFixture = existsSync(FIXTURE) ? describe : describe.skip

describeIfFixture('onnxruntime-web end to end', () => {
  it('loads the model, runs it, and decodes the same box as the server', async () => {
    const ort = await import('onnxruntime-web')
    const session = await ort.InferenceSession.create(readFileSync(FIXTURE), {
      executionProviders: ['wasm'],
    })

    const inputName = session.inputNames[0]
    const input = new ort.Tensor('float32', new Float32Array(1 * 3 * 640 * 640), [1, 3, 640, 640])
    const output = await session.run({ [inputName]: input })
    const tensor = output[session.outputNames[0]]

    // The fixture encodes one late blight box at cx=320 cy=320 w=200 h=100,
    // conf 0.88 -- identical to the Python fixture.
    expect(tensor.dims[1]).toBe(4 + CLASS_NAMES.length)

    const detections = decodeDetections(tensor.data, tensor.dims, {
      classNames: CLASS_NAMES,
      defaultThreshold: 0.25,
      iouThreshold: 0.45,
      letterbox: letterboxParams(640, 480, 640),
      sourceWidth: 640,
      sourceHeight: 480,
    })

    expect(detections).toHaveLength(1)
    const [d] = detections
    expect(d.classKey).toBe('potato_late_blight')
    expect(d.confidence).toBeCloseTo(0.88, 4)
    // Exactly the expectation asserted in backend/tests/test_onnx_integration.py.
    expect(d.bbox[0]).toBeCloseTo(220, 1)
    expect(d.bbox[1]).toBeCloseTo(190, 1)
    expect(d.bbox[2]).toBeCloseTo(420, 1)
    expect(d.bbox[3]).toBeCloseTo(290, 1)
  }, 60000)
})
